version: '3'

services:
  ventas:
    build: ventas-1
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://ventas_server:3306/ventas?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USER_NAME=root
      - DB_PASSWORD=root
    restart: always
    depends_on:
      ventas_server:
        condition: service_healthy
  ventas_server:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ventas
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10


